@startuml
class BytesToImageConverter {
    - {static} _converter : BytesToImageConverter?
    + <<override>> ProvideValue(serviceProvider:IServiceProvider) : object
    + Convert(value:object, targetType:Type, parameter:object, culture:CultureInfo) : object
    + ConvertBack(value:object, targetType:Type, parameter:object, culture:CultureInfo) : object
}
MarkupExtension <|-- BytesToImageConverter
IValueConverter <|-- BytesToImageConverter
@enduml
